# This is the configuration @ajhalili2006 uses for deploying some of RecapTime.dev's infra
# over Hack Club Nest. The contents of the env_files as used by the services below is only
# available at the original private repository due to security reasons.

services:
  # Database services
  postgres:
    networks:
    - rtdev_internal
    - ajhalili2006
    image: postgres:17-alpine
    pull_policy: always
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - 43919:5432
  mysql:
    networks:
    - rtdev_internal
    image: mysql:8
    pull_policy: always
    restart: unless-stopped
    command: ["mysqld", "--innodb-use-native-aio=0"]
    env_file:
      - db.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 42635:3306
  redis:
    image: redis:alpine
    pull_policy: always
    command: --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - rtdev_internal
    env_file:
      - db.env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    ports:
      - 38247:6379
    volumes:
      - redis-data:/data
  
  # services
  vault:
    pull_policy: always
    image: ghcr.io/recaptime-dev/vaultwarden-docker:nightly
    env_file:
      - vaultwarden.env
    volumes:
      - vw-data:/data
    ports:
      - 34095:3000
    networks:
      - rtdev_internal
  ghost:
    pull_policy: always
    image: ghost:5-alpine
    restart: unless-stopped
    networks:
      - rtdev_internal
    env_file:
      - db.env
      - ghost.env
    ports:
      - 33881:2368
    volumes:
      - ghost-data:/var/lib/ghost/content
  
  # 1Password Connect Servers
  op-connect-api:
    pull_policy: always
    image: 1password/connect-api:latest
    ports:
      - "34715:8080"
      - "46859:8081"
    volumes:
      - "op-connect-data:/home/opuser/.op/data"
    env_file:
      - op-connect.env
  op-connect-sync:
    pull_policy: always
    image: 1password/connect-sync:latest
    ports:
      - "43189:8080"
    volumes:
      - "op-connect-data:/home/opuser/.op/data"
    env_file:
      - op-connect.env

networks:
  rtdev_internal:
    name: recaptime-dev
    external: true
  ajhalili2006:
    name: personal-infra
    external: true

volumes:
  tsdproxy-datadir:
  postgres-data:
  mysql-data:
  redis-data:
  ghost-data:
    name: ghost-data-recaptimedev
    external: true
  vw-data:
  op-connect-data:
