# This is the configuration @ajhalili2006 uses for deploying some of RecapTime.dev's infra
# over Hack Club Nest. The contents of the stack.env is only available at the original
# private repository due to security reasons.

services:
  # Database services
  postgres:
    networks:
    - rtdev_internal
    - ajhalili2006
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - 43919:5432
  mysql:
    networks:
    - rtdev_internal
    image: mysql:8
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 42635:3306
  redis:
    image: redis:alpine
    command: --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - rtdev_internal
    env_file:
      - db.env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    ports:
      - 38247:6379
    volumes:
      - redis-data:/data
  
  # services
  vault:
    image: ghcr.io/recaptime-dev/vaultwarden-docker:nightly
    env_file:
      - vaultwarden.env
    volumes:
      - vw-data:/data
    ports:
      - 34095:3000
    networks:
      - rtdev_internal
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    networks:
      - rtdev_internal
    env_file:
      - db.env
      - ghost.env
    ports:
      - 33881:2368

networks:
  rtdev_internal:
    name: recaptime-dev
    external: true
  ajhalili2006:
    name: personal-infra
    external: true

volumes:
  tsdproxy-datadir:
  postgres-data:
  mysql-data:
  redis-data:
  ghost-data:
    name: ghost-data-recaptimedev
    external: true
  vw-data:
